// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAEsde99-ke8okJXBrR48VgKOpZmzQycc',
    appId: '1:1032377922268:web:515a97c922e5826fa67a19',
    messagingSenderId: '1032377922268',
    projectId: 'testing-cli-97b0c',
    authDomain: 'testing-cli-97b0c.firebaseapp.com',
    storageBucket: 'testing-cli-97b0c.appspot.com',
    measurementId: 'G-8F8ZP6WCKG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyU-MsQcBPkXl1j09qUYeLWOM3mEjF-LE',
    appId: '1:1032377922268:android:8f58baf0739d453fa67a19',
    messagingSenderId: '1032377922268',
    projectId: 'testing-cli-97b0c',
    storageBucket: 'testing-cli-97b0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9xn6GuWiRpAgZCV4iKA3BOiNW4BX07-0',
    appId: '1:1032377922268:ios:7f71d57b73378c11a67a19',
    messagingSenderId: '1032377922268',
    projectId: 'testing-cli-97b0c',
    storageBucket: 'testing-cli-97b0c.appspot.com',
    iosBundleId: 'com.example.bestFlutterUiTemplates',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9xn6GuWiRpAgZCV4iKA3BOiNW4BX07-0',
    appId: '1:1032377922268:ios:863e843b1b978ddfa67a19',
    messagingSenderId: '1032377922268',
    projectId: 'testing-cli-97b0c',
    storageBucket: 'testing-cli-97b0c.appspot.com',
    iosBundleId: 'Y',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAEsde99-ke8okJXBrR48VgKOpZmzQycc',
    appId: '1:1032377922268:web:c78716a61b2fb68ba67a19',
    messagingSenderId: '1032377922268',
    projectId: 'testing-cli-97b0c',
    authDomain: 'testing-cli-97b0c.firebaseapp.com',
    storageBucket: 'testing-cli-97b0c.appspot.com',
    measurementId: 'G-B43KLEC2HY',
  );
}
